# ═════ Packages to publish ═════



# ═════ Unchanged packages ═════

["@publisher/core"]
publish = false
version = "0.1.2"

["@publisher/deployment-handler"]
publish = false
version = "0.1.2"

["@publisher/id-generator"]
publish = false
version = "0.1.1"

["@publisher/npm-auth"]
publish = false
version = "0.1.1"

["@publisher/npm-helpers"]
publish = false
version = "0.1.1"

["@publisher/probot-app"]
publish = false
version = "0.1.4"

["@publisher/push-handler"]
publish = false
version = "0.1.2"

["@publisher/rush-helpers"]
publish = false
version = "0.1.1"

["@publisher/yarn-helpers"]
publish = false
version = "0.1.1"


