# ═════ Packages to publish ═════

["@publisher/core"]
# prior : "0.1.3"
version = "TODO"

["@publisher/deployment-handler"]
# prior : "0.1.3"
version = "TODO"

["@publisher/probot-app"]
# prior : "0.1.9"
version = "TODO"

["@publisher/push-handler"]
# prior : "0.1.3"
version = "TODO"

["@publisher/rush-helpers"]
# prior : "0.1.2"
version = "TODO"

# ═════ Unchanged packages ═════

["@publisher/id-generator"]
publish = false
version = "0.1.2"

["@publisher/npm-auth"]
publish = false
version = "0.1.4"

["@publisher/npm-helpers"]
publish = false
version = "0.1.2"

["@publisher/yarn-helpers"]
publish = false
version = "0.1.2"


