# ═════ Packages to publish ═════

["@publisher/probot-app"]
# prior : "0.1.0"
version = "0.1.1"

["@publisher/rush-helpers"]
version = "0.1.0"

# ═════ Unchanged packages ═════

["@publisher/core"]
publish = false
version = "0.1.0"

["@publisher/deployment-handler"]
publish = false
version = "0.1.0"

["@publisher/id-generator"]
publish = false
version = "0.1.0"

["@publisher/npm-auth"]
publish = false
version = "0.1.0"

["@publisher/npm-helpers"]
publish = false
version = "0.1.0"

["@publisher/push-handler"]
publish = false
version = "0.1.0"

["@publisher/yarn-helpers"]
publish = false
version = "0.1.0"


