on: deployment
name: Deployment handler
jobs:
  handleDeployment:
    name: Handle deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Handle deployment
        uses: publisher/gh-actions/deployment@ab652c63e792e125229c06659697da1274108b18
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
