on: push
name: Push handler
jobs:
  handlePush:
    name: Handle push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Handle push
        uses: publisher/gh-actions/push@ab652c63e792e125229c06659697da1274108b18
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
